"""empty message

Revision ID: 020d7de6a433
Revises: 36fccbbd0f52
Create Date: 2021-11-08 13:18:21.502595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '020d7de6a433'
down_revision = '36fccbbd0f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reservation', 'seat', ['seat_id'], ['id'])
    op.drop_column('reservation', 'seat_number')
    op.drop_column('reservation', 'movie_id')
    op.add_column('screen', sa.Column('theater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'screen', 'theater', ['theater_id'], ['id'])
    op.add_column('seat', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('seat', sa.Column('row', sa.String(length=1), nullable=False))
    op.add_column('seat', sa.Column('col', sa.Integer(), nullable=False))
    op.add_column('seat', sa.Column('seattype_type', sa.String(length=10), nullable=True))
    op.add_column('seat', sa.Column('seattype_price', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seat', 'seattype', ['seattype_price'], ['price'])
    op.create_foreign_key(None, 'seat', 'seattype', ['seattype_type'], ['type'])
    op.drop_column('seat', 'number')
    op.drop_column('seat', 'type')
    op.drop_column('seat', 'seatprice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('seatprice', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('seat', sa.Column('type', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('seat', sa.Column('number', mysql.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'seat', type_='foreignkey')
    op.drop_constraint(None, 'seat', type_='foreignkey')
    op.drop_column('seat', 'seattype_price')
    op.drop_column('seat', 'seattype_type')
    op.drop_column('seat', 'col')
    op.drop_column('seat', 'row')
    op.drop_column('seat', 'id')
    op.drop_constraint(None, 'screen', type_='foreignkey')
    op.drop_column('screen', 'theater_id')
    op.add_column('reservation', sa.Column('movie_id', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('reservation', sa.Column('seat_number', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    # ### end Alembic commands ###
