"""empty message

Revision ID: 0dcfd748c081
Revises: c361ac0936a9
Create Date: 2021-11-11 23:34:05.748538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dcfd748c081'
down_revision = 'c361ac0936a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theater', 'screen')
    op.drop_column('theater', 'address')
    op.drop_column('theater', 'seat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theater', sa.Column('seat', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('theater', sa.Column('address', mysql.VARCHAR(length=27), nullable=True))
    op.add_column('theater', sa.Column('screen', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
