"""empty message

Revision ID: 2db8a02f2bd5
Revises: 3cafe112a9fa
Create Date: 2021-11-03 22:26:20.394603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2db8a02f2bd5'
down_revision = '3cafe112a9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'pw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('pw', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
