"""empty message

Revision ID: 3cafe112a9fa
Revises: 473d899dd068
Create Date: 2021-11-03 22:23:44.030177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cafe112a9fa'
down_revision = '473d899dd068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'password')
    # ### end Alembic commands ###
