"""empty message

Revision ID: 473d899dd068
Revises: b8c54e0be99f
Create Date: 2021-11-03 22:21:47.688573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473d899dd068'
down_revision = 'b8c54e0be99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'password')
    # ### end Alembic commands ###
