"""empty message

Revision ID: 656e743706a6
Revises: afabc8a44a08
Create Date: 2021-11-19 23:42:54.360943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '656e743706a6'
down_revision = 'afabc8a44a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('title', sa.String(length=45), nullable=False))
    op.add_column('notice', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('notice', sa.Column('theater_id', sa.Integer(), nullable=True))
    op.alter_column('notice', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'notice', 'theater', ['theater_id'], ['id'])
    op.drop_column('notice', 'create_date')
    op.drop_column('notice', 'subject')
    op.drop_column('question', 'member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('notice', sa.Column('subject', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('notice', sa.Column('create_date', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'notice', type_='foreignkey')
    op.alter_column('notice', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('notice', 'theater_id')
    op.drop_column('notice', 'date')
    op.drop_column('notice', 'title')
    # ### end Alembic commands ###
