"""empty message

Revision ID: 7fcbd1a6fa46
Revises: ddc832486000
Create Date: 2021-12-03 00:45:43.337167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fcbd1a6fa46'
down_revision = 'ddc832486000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiry_answer')
    op.add_column('cancel', sa.Column('usingcoupon', sa.Integer(), nullable=False))
    op.drop_constraint('cancel_ibfk_2', 'cancel', type_='foreignkey')
    op.drop_column('cancel', 'res_id')
    op.add_column('pay', sa.Column('discountpay', sa.Integer(), nullable=False))
    op.add_column('pay', sa.Column('lastpay', sa.Integer(), nullable=False))
    op.drop_column('pay', 'coupon_code')
    op.drop_column('pay', 'used_points')
    op.add_column('question', sa.Column('member_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'question', 'member', ['member_id'], ['id'], ondelete='CASCADE')
    op.add_column('reservation', sa.Column('seat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'seat', ['seat_id'], ['id'])
    op.drop_column('reservation', 'seats')
    op.drop_column('review', 'sentiment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('sentiment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('seats', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'seat_id')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'member_id')
    op.add_column('pay', sa.Column('used_points', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('pay', sa.Column('coupon_code', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('pay', 'lastpay')
    op.drop_column('pay', 'discountpay')
    op.add_column('cancel', sa.Column('res_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('cancel_ibfk_2', 'cancel', 'reservation', ['res_id'], ['id'])
    op.drop_column('cancel', 'usingcoupon')
    op.create_table('inquiry_answer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry.number'], name='inquiry_answer_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
