"""empty message

Revision ID: 86d2cffb076f
Revises: 01c931ef89b8
Create Date: 2021-11-08 00:03:33.629554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86d2cffb076f'
down_revision = '01c931ef89b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screenschedule', 'screen_number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('screenschedule', 'movie_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('screenschedule', 'theater_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screenschedule', 'theater_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('screenschedule', 'movie_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('screenschedule', 'screen_number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
