"""empty message

Revision ID: 954b9c2c32c5
Revises: 7c99f8db3a7c
Create Date: 2021-11-08 13:22:39.365465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '954b9c2c32c5'
down_revision = '7c99f8db3a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('theater_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.drop_table('seattype')
    op.create_foreign_key(None, 'reservation', 'seat', ['seat_number'], ['number'])
    op.drop_column('reservation', 'seat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('seat_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_table('seattype',
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('type'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('notice')
    # ### end Alembic commands ###
