"""empty message

Revision ID: a62b4cc5565a
Revises: cd042faa3312
Create Date: 2021-11-20 04:12:50.494107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62b4cc5565a'
down_revision = 'cd042faa3312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay', sa.Column('method', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay', 'method')
    # ### end Alembic commands ###
