"""empty message

Revision ID: afabc8a44a08
Revises: 362e882535bf
Create Date: 2021-11-19 23:06:38.180282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afabc8a44a08'
down_revision = '362e882535bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice_answer')
    op.add_column('notice', sa.Column('title', sa.String(length=45), nullable=False))
    op.add_column('notice', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('notice', sa.Column('theater_id', sa.Integer(), nullable=True))
    op.alter_column('notice', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'notice', 'theater', ['theater_id'], ['id'])
    op.drop_column('notice', 'create_date')
    op.drop_column('notice', 'subject')
    op.drop_column('question', 'member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('notice', sa.Column('subject', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('notice', sa.Column('create_date', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'notice', type_='foreignkey')
    op.alter_column('notice', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('notice', 'theater_id')
    op.drop_column('notice', 'date')
    op.drop_column('notice', 'title')
    op.create_table('notice_answer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('notice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notice.id'], name='notice_answer_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
