"""empty message

Revision ID: c3255572d013
Revises: 932786e4509c
Create Date: 2021-11-05 15:50:45.749158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3255572d013'
down_revision = '932786e4509c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('eng_title', sa.String(length=45), nullable=False))
    op.add_column('movie', sa.Column('release', sa.Date(), nullable=False))
    op.add_column('movie', sa.Column('country', sa.String(length=20), nullable=False))
    op.add_column('movie', sa.Column('language', sa.String(length=20), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('movie', 'language')
    op.drop_column('movie', 'country')
    op.drop_column('movie', 'release')
    op.drop_column('movie', 'eng_title')
    # ### end Alembic commands ###
