"""empty message

Revision ID: c361ac0936a9
Revises: c4a199e47b8f
Create Date: 2021-11-10 21:05:57.585446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c361ac0936a9'
down_revision = 'c4a199e47b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('membership_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'member', 'membership', ['membership_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('member', 'membership_id')
    # ### end Alembic commands ###
