"""empty message

Revision ID: f0ed3b158f62
Revises: d1f591944138
Create Date: 2021-11-26 07:12:09.348564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ed3b158f62'
down_revision = 'd1f591944138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay', sa.Column('method', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay', 'method')
    # ### end Alembic commands ###
