"""empty message

Revision ID: fb7684581c0a
Revises: be3ebe1ded28
Create Date: 2021-11-08 13:51:32.490415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb7684581c0a'
down_revision = 'be3ebe1ded28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=25), nullable=False),
    sa.Column('authority', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('department', 'position')
    )
    op.create_table('employee',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('pw', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('theater_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commute', sa.Column('employee_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'commute', 'employee', ['employee_id'], ['id'])
    op.drop_column('commute', 'user_id')
    op.add_column('evaluation', sa.Column('employee_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'evaluation', 'employee', ['employee_id'], ['id'])
    op.add_column('schedulemanage', sa.Column('employee_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'schedulemanage', 'employee', ['employee_id'], ['id'])
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=False))
    op.add_column('user', sa.Column('salary', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('account', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('department_info', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('theater_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'user', 'theater', ['theater_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'theater_id')
    op.drop_column('user', 'department_info')
    op.drop_column('user', 'account')
    op.drop_column('user', 'salary')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'age')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'gender')
    op.drop_constraint(None, 'schedulemanage', type_='foreignkey')
    op.drop_column('schedulemanage', 'employee_id')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_column('evaluation', 'employee_id')
    op.add_column('commute', sa.Column('user_id', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=True))
    op.drop_constraint(None, 'commute', type_='foreignkey')
    op.drop_column('commute', 'employee_id')
    op.drop_table('employee')
    op.drop_table('info')
    # ### end Alembic commands ###
