"""empty message

Revision ID: fbefa02d614f
Revises: e1522dbd2f71
Create Date: 2021-11-20 01:06:57.136561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbefa02d614f'
down_revision = 'e1522dbd2f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay', 'method')
    op.alter_column('reservation', 'seat_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=1000),
               nullable=False)
    op.drop_constraint('reservation_ibfk_4', 'reservation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reservation_ibfk_4', 'reservation', 'seat', ['seat_id'], ['id'])
    op.alter_column('reservation', 'seat_id',
               existing_type=sa.String(length=1000),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('pay', sa.Column('method', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
