"""empty message

Revision ID: fc5bc5b89662
Revises: a62b4cc5565a
Create Date: 2021-11-26 07:08:09.662770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc5bc5b89662'
down_revision = 'a62b4cc5565a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nonmember', 'pw',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('nonmember', 'birth_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('pay', sa.Column('method', sa.String(length=20), nullable=False))
    op.alter_column('review', 'rate',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('review', 'modify_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('modify_date', mysql.DATETIME(), nullable=True))
    op.alter_column('review', 'rate',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_column('pay', 'method')
    op.alter_column('nonmember', 'birth_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('nonmember', 'pw',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
